apiVersion: v1
kind: Service
metadata:
  name: pitgo-backend-service
  namespace: pitgo
spec:
  selector:
    app: pitgo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
