apiVersion: v1
kind: ConfigMap
metadata:
  name: pitgo-backend-config
  namespace: pitgo
data:
  APP_PORT: "8080"
  APP_ENV: "production"
  DB_HOST: "postgres-service.pitgo.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "pitgo"
  DB_SSL_MODE: "require"
  REDIS_ADDR: "redis-service.pitgo.svc.cluster.local:6379"
  QUEUE_DRIVER: "memory"
  RATE_LIMIT_RPS: "20"
  RATE_LIMIT_BURST: "40"
