apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pitgo-ingress
  namespace: pitgo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rate-limit: "30"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: api.pitgo.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pitgo-backend-service
                port:
                  number: 80
  tls:
    - hosts:
        - api.pitgo.app
      secretName: pitgo-tls-secret
